M48
; DRILL file {KiCad 8.0.1} date 2025-03-07T14:58:41+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-07T14:58:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.0205Y-3.2949
X3.0205Y-6.4992
X5.2272Y-3.2949
X5.2272Y-6.5012
M30
